export type GenreGuideEntry = {
  id: string;
  name: string;
  summary: string;
  mechanics: string[];
  famousGames: string[];
  subgenres: string[];
  tags: string[];
};

export const genreGuideEntries: GenreGuideEntry[] = [
  {
    id: 'platformer',
    name: 'Platformer',
    summary: 'Movement games built around jumping, timing, traversal, and spatial rhythm.',
    mechanics: ['Jump arcs', 'Gravity', 'Hazard timing', 'Collectibles', 'Checkpoint flow'],
    famousGames: ['Super Mario Bros.', 'Sonic the Hedgehog', 'Celeste'],
    subgenres: ['2D platformer', '3D platformer', 'Precision platformer', 'Metroidvania'],
    tags: ['Side view', 'Exploration', 'Collectathon', 'Speedrunning'],
  },
  {
    id: 'shooter',
    name: 'Shooter',
    summary: 'Action games where aiming, firing, positioning, and target priority drive play.',
    mechanics: ['Aiming', 'Target priority', 'Line of sight', 'Ammo rhythm', 'Cover or evasive movement'],
    famousGames: ['Doom', 'Half-Life 2', 'Halo: Combat Evolved'],
    subgenres: ['First-person shooter', 'Third-person shooter', 'Hero shooter', 'Shoot em up'],
    tags: ['Action', 'Sci-fi', 'Arena', 'Tactical'],
  },
  {
    id: 'puzzle',
    name: 'Puzzle',
    summary: 'Games centered on problem solving, pattern recognition, rules, and clever constraints.',
    mechanics: ['Rule discovery', 'Pattern matching', 'Spatial reasoning', 'Sequencing', 'Constraint solving'],
    famousGames: ['Tetris', 'Portal', 'The Witness'],
    subgenres: ['Tile matching', 'Logic puzzle', 'Physics puzzle', 'Hidden object'],
    tags: ['Abstract', 'Minimal', 'Single-player', 'Brain teaser'],
  },
  {
    id: 'rpg',
    name: 'Role-playing Game',
    summary: 'Character-centered games about growth, choices, stats, quests, and long-form progression.',
    mechanics: ['Character progression', 'Stats and builds', 'Dialogue choices', 'Inventory', 'Quest structure'],
    famousGames: ['Final Fantasy VII', 'The Elder Scrolls V: Skyrim', "Baldur's Gate 3"],
    subgenres: ['JRPG', 'Action RPG', 'Tactical RPG', 'MMORPG'],
    tags: ['Fantasy', 'Story-rich', 'Open world', 'Party-based'],
  },
  {
    id: 'strategy',
    name: 'Strategy',
    summary: 'Decision-heavy games about planning, resources, positioning, and long-term advantage.',
    mechanics: ['Resource management', 'Unit control', 'Map control', 'Tech progression', 'Tactical tradeoffs'],
    famousGames: ['Civilization', 'StarCraft', 'XCOM: Enemy Unknown'],
    subgenres: ['RTS', 'Turn-based strategy', '4X', 'Tactics'],
    tags: ['War', 'Economy', 'Base building', 'Competitive'],
  },
  {
    id: 'racing',
    name: 'Racing',
    summary: 'Competition games about speed, racing lines, vehicle handling, and reaction windows.',
    mechanics: ['Acceleration', 'Braking', 'Racing line', 'Drifting', 'Opponent pressure'],
    famousGames: ['Gran Turismo', 'Mario Kart 8', 'Forza Horizon 5'],
    subgenres: ['Arcade racing', 'Racing simulation', 'Kart racing', 'Combat racing'],
    tags: ['Driving', 'Sports', 'Time trial', 'Open world'],
  },
  {
    id: 'sports',
    name: 'Sports',
    summary: 'Games that translate athletic rules, timing, teamwork, and competition into play.',
    mechanics: ['Aiming or timing', 'Team positioning', 'Rule simulation', 'Stamina or momentum', 'Scoring windows'],
    famousGames: ['FIFA International Soccer', 'NBA 2K11', 'Wii Sports'],
    subgenres: ['Football/soccer', 'Basketball', 'Tennis', 'Arcade sports'],
    tags: ['Simulation', 'Local multiplayer', 'Competitive', 'Management'],
  },
  {
    id: 'fighting',
    name: 'Fighting',
    summary: 'Competitive combat games about spacing, timing, reads, combos, and direct matchups.',
    mechanics: ['Spacing', 'Blocking', 'Combos', 'Punishes', 'Frame advantage'],
    famousGames: ['Street Fighter II', 'Mortal Kombat', 'Tekken 3'],
    subgenres: ['2D fighter', '3D fighter', 'Platform fighter', 'Arena fighter'],
    tags: ['Versus', 'Arcade', 'Local multiplayer', 'Competitive'],
  },
  {
    id: 'simulation',
    name: 'Simulation',
    summary: 'System-driven games that model activities, machines, ecosystems, or real-world processes.',
    mechanics: ['System modeling', 'Parameter tuning', 'Cause and effect', 'Growth curves', 'Scenario management'],
    famousGames: ['SimCity', 'The Sims', 'Microsoft Flight Simulator'],
    subgenres: ['Life sim', 'Vehicle sim', 'City builder', 'Management sim'],
    tags: ['Sandbox', 'Creative', 'Economy', 'Realistic'],
  },
  {
    id: 'soulslike',
    name: 'Souls Like',
    summary: 'Methodical action RPGs about stamina, pattern reading, harsh death loops, and earned mastery.',
    mechanics: ['Stamina and animation commitment', 'Dodge, guard, or parry timing', 'Bonfire-style checkpoints', 'Death recovery loop', 'Boss pattern learning'],
    famousGames: ["Demon's Souls", 'Dark Souls', 'Elden Ring'],
    subgenres: ['Action RPG soulslike', '2D soulslike', 'Soulsborne', 'Boss-rush soulslike'],
    tags: ['High difficulty', 'Stamina combat', 'Dark fantasy', 'Environmental storytelling'],
  },
  {
    id: 'adventure',
    name: 'Adventure',
    summary: 'Narrative-driven games centered on exploration, discovery, puzzles, and story progression.',
    mechanics: ['Exploration', 'Environmental puzzles', 'Dialogue choices', 'Inventory management', 'Story progression'],
    famousGames: ['The Secret of Monkey Island', 'Grim Fandango', 'Life is Strange'],
    subgenres: ['Point-and-click', 'Text adventure', 'Interactive drama', 'Narrative adventure'],
    tags: ['Story-rich', 'Puzzle-solving', 'Mystery', 'Character-driven'],
  },
  {
    id: 'metroidvania',
    name: 'Metroidvania',
    summary: 'Exploration games with interconnected worlds, ability-gated progression, and backtracking.',
    mechanics: ['Ability gating', 'Interconnected maps', 'Backtracking', 'Secret discovery', 'Boss progression'],
    famousGames: ['Metroid', 'Castlevania: Symphony of the Night', 'Hollow Knight'],
    subgenres: ['Action Metroidvania', '3D Metroidvania', 'Pixel-art Metroidvania', 'Atmospheric Metroidvania'],
    tags: ['Exploration', 'Non-linear', 'Platforming', 'Boss fights'],
  },
  {
    id: 'roguelike',
    name: 'Roguelike',
    summary: 'Turn-based dungeon-crawlers with procedural generation, permanent death, and increasing runs.',
    mechanics: ['Turn-based exploration', 'Permanent death', 'Procedural generation', 'Item synergy', 'Tactical depth'],
    famousGames: ['Rogue', 'Nethack', 'Hades'],
    subgenres: ['Dungeon crawler', 'Tactical roguelike', 'Action roguelike', 'Coffee-break roguelike'],
    tags: ['Turn-based', 'Procedural', 'Death mechanics', 'Replayability'],
  },
  {
    id: 'roguelite',
    name: 'Roguelite',
    summary: 'Action games with procedural generation, permadeath, and persistent progression across runs.',
    mechanics: ['Procedural generation', 'Permanent death', 'Persistent upgrades', 'Action-based combat', 'Run-based progression'],
    famousGames: ['The Binding of Isaac', 'Spelunky', 'Dead Cells'],
    subgenres: ['Shooter roguelite', 'Action roguelite', 'Platformer roguelite', 'Deck-building roguelite'],
    tags: ['Action', 'Replayability', 'Procedural', 'Persistent progression'],
  },
  {
    id: 'actionrpg',
    name: 'Action RPG',
    summary: 'Character progression games where real-time combat and skill execution matter as much as stats.',
    mechanics: ['Character progression', 'Real-time combat', 'Equipment and stat growth', 'Skill execution', 'Exploration'],
    famousGames: ['The Legend of Zelda: Ocarina of Time', 'Monster Hunter', 'Dark Souls'],
    subgenres: ['Hack-and-slash', 'Character-driven action RPG', 'Boss-rush action RPG', 'Loot-based action RPG'],
    tags: ['Combat-focused', 'Exploration', 'Progression', 'Real-time action'],
  },
  {
    id: 'mmorpg',
    name: 'MMORPG',
    summary: 'Multiplayer role-playing games where players cooperate or compete in persistent shared worlds.',
    mechanics: ['Character progression', 'Questing', 'Social bonds', 'Dungeons and raids', 'Economy and crafting'],
    famousGames: ['World of Warcraft', 'Final Fantasy XIV', 'Guild Wars 2'],
    subgenres: ['Fantasy MMORPG', 'Action MMORPG', 'Sci-fi MMORPG', 'Sandbox MMORPG'],
    tags: ['Multiplayer', 'Community', 'Persistent world', 'Long-form progression'],
  },
  {
    id: 'moba',
    name: 'MOBA',
    summary: 'Team-based action strategy games about objective control, character ability synergies, and team coordination.',
    mechanics: ['Hero selection', 'Leveling and ability upgrades', 'Map objectives', 'Team coordination', 'Economic tradeoffs'],
    famousGames: ['League of Legends', 'Dota 2', 'Heroes of the Storm'],
    subgenres: ['Lane-based MOBA', 'Objective-focused MOBA', 'Fantasy MOBA', 'Mobile MOBA'],
    tags: ['Competitive', 'Team-based', 'Esports', 'Tactical'],
  },
  {
    id: 'cardgame',
    name: 'Card Game',
    summary: 'Games centered on deck-building, card synergies, and strategic decision-making with a limited hand.',
    mechanics: ['Deck-building', 'Hand management', 'Resource economy', 'Card synergy', 'Turn structure'],
    famousGames: ['Magic: The Gathering', 'Hearthstone', 'Slay the Spire'],
    subgenres: ['Trading card game', 'Collectible card game', 'Deck-building roguelike', 'Auto-battler card game'],
    tags: ['Strategy', 'Deck-building', 'Turn-based', 'Competitive'],
  },
  {
    id: 'rhythm',
    name: 'Rhythm',
    summary: 'Music-driven games where timing button presses or gestures to beat patterns is the core challenge.',
    mechanics: ['Timing precision', 'Beat reading', 'Input sequencing', 'Scoring multipliers', 'Visual feedback'],
    famousGames: ['Dance Dance Revolution', 'Guitar Hero', 'Crypt of the NecroDancer'],
    subgenres: ['Dance game', 'Guitar/instrument simulator', 'Rhythm action', 'Music puzzle'],
    tags: ['Music', 'Timing', 'Precision', 'Flow state'],
  },
  {
    id: 'survival',
    name: 'Survival',
    summary: 'Resource management games where players balance hunger, health, crafting, and environmental threats.',
    mechanics: ['Resource gathering', 'Crafting', 'Health/hunger management', 'Base building', 'Environmental hazards'],
    famousGames: ['Minecraft', "Don't Starve", 'The Long Dark'],
    subgenres: ['Crafting survival', 'Sandbox survival', 'Simulation survival', 'Urban survival'],
    tags: ['Resource management', 'Base building', 'Exploration', 'Permadeath'],
  },
  {
    id: 'visualnovel',
    name: 'Visual Novel',
    summary: 'Narrative experiences with branching choices, character relationships, and story-driven gameplay.',
    mechanics: ['Dialogue choices', 'Story branching', 'Character relationships', 'Multiple endings', 'Text progression'],
    famousGames: ['Steins;Gate', 'Doki Doki Literature Club', 'Hades'],
    subgenres: ['Dating sim', 'Kinetic novel', 'Interactive fiction', 'Story-driven visual novel'],
    tags: ['Story-rich', 'Narrative choice', 'Character-driven', 'Text-based'],
  },
  {
    id: 'tacticalrpg',
    name: 'Tactical RPG',
    summary: 'Turn-based strategy games combining RPG progression with grid-based tactical combat.',
    mechanics: ['Grid-based positioning', 'Turn-based combat', 'Character leveling', 'Terrain advantage', 'Squad composition'],
    famousGames: ['Fire Emblem', 'XCOM 2', 'Divinity: Original Sin 2'],
    subgenres: ['Grid-based tactics', 'Squad command', 'Isometric TRPG', 'Story-driven tactics'],
    tags: ['Turn-based', 'Strategic positioning', 'Character progression', 'Story-rich'],
  },
  {
    id: 'deckbuilder',
    name: 'Deck Builder',
    summary: 'Strategy games where building and tuning a custom deck of cards is central to winning.',
    mechanics: ['Deck construction', 'Card synergy', 'Resource economy', 'Meta-game', 'Strategic building'],
    famousGames: ['Magic: The Gathering Arena', 'Legends of Runeterra', 'Marvel Snap'],
    subgenres: ['Competitive deck-builder', 'Digital CCG', 'Limited deck-building', 'Roguelike deck-builder'],
    tags: ['Strategy', 'Deck construction', 'Meta-game', 'Collection'],
  },
  {
    id: 'turnbasedstrategy',
    name: 'Turn-Based Strategy',
    summary: 'Large-scale strategy games where planning, positioning, and economy develop across extended turns.',
    mechanics: ['Resource management', 'Territory control', 'Diplomacy', 'Technology trees', 'Military planning'],
    famousGames: ['Civilization VI', 'Total War: Warhammer III', 'Crusader Kings III'],
    subgenres: ['4X', 'Grand strategy', 'Wargame', 'Asynchronous strategy'],
    tags: ['Planning', 'Diplomacy', 'Long-form', 'Competitive'],
  },
  {
    id: 'realtimestrategy',
    name: 'Real-Time Strategy',
    summary: 'Action strategy games where resource gathering, base building, and unit production happen in real-time.',
    mechanics: ['Base building', 'Resource gathering', 'Unit production', 'Micromanagement', 'Real-time tactics'],
    famousGames: ['StarCraft II', 'Age of Empires IV', 'They Are Billions'],
    subgenres: ['Sci-fi RTS', 'Historical RTS', 'Tower defense RTS', 'MOBA-inspired RTS'],
    tags: ['Real-time', 'Base management', 'Competitive', 'Esports'],
  },
  {
    id: 'idleclicker',
    name: 'Idle/Clicker',
    summary: 'Games where progress happens through repetitive actions or passive generation while player is away.',
    mechanics: ['Clicking/tapping', 'Passive income', 'Incremental growth', 'Automation', 'Prestige resets'],
    famousGames: ['Cookie Clicker', 'Adventure Capitalist', 'Clicker Heroes'],
    subgenres: ['Idle RPG', 'Incremental clicker', 'Resource idle', 'Automation idle'],
    tags: ['Incremental', 'Casual', 'Numbers go up', 'Automation'],
  },
  {
    id: 'dungeoncrawler',
    name: 'Dungeon Crawler',
    summary: 'Exploration games about navigating dangerous labyrinths, loot, enemies, and hidden rooms.',
    mechanics: ['Room exploration', 'Loot discovery', 'Enemy encounters', 'Mapping', 'Resource attrition'],
    famousGames: ['Dungeon Master', 'Diablo', 'Everspace'],
    subgenres: ['Grid-based dungeon crawler', 'FPS dungeon crawler', 'Sci-fi dungeon crawler', 'Roguelike dungeon crawler'],
    tags: ['Exploration', 'Loot', 'Danger', 'Mystery'],
  },
  {
    id: 'hacknslash',
    name: 'Hack and Slash',
    summary: 'Action games focused on melee combat, combo chains, enemy waves, and stylish execution.',
    mechanics: ['Melee combos', 'Crowd control', 'Enemy waves', 'Dodging', 'Weapon variety'],
    famousGames: ['Devil May Cry', 'God of War', 'Bayonetta'],
    subgenres: ['Character action', 'Action RPG hack-and-slash', 'Musou', 'Arena brawler'],
    tags: ['Action', 'Combos', 'Melee', 'Style'],
  },
  {
    id: 'twinstickshooter',
    name: 'Twin-Stick Shooter',
    summary: 'Shooter games where movement and aiming are controlled independently, often in arenas.',
    mechanics: ['Independent movement and aiming', 'Enemy swarms', 'Arena control', 'Power-ups', 'Dodging'],
    famousGames: ['Robotron: 2084', 'Geometry Wars', 'Binding of Isaac'],
    subgenres: ['Arcade twin-stick', 'Roguelike twin-stick', 'Bullet-hell twin-stick', 'Cooperative twin-stick'],
    tags: ['Arcade', 'Precision', 'Action', 'Crowd control'],
  },
  {
    id: 'shmup',
    name: 'Shmup',
    summary: 'Shoot-em-up games where vertical or horizontal scrolling and bullet dodging are central challenges.',
    mechanics: ['Bullet dodging', 'Scrolling movement', 'Power-up collection', 'Pattern learning', 'Scoring multipliers'],
    famousGames: ['Galaga', 'Touhou Project', '1942'],
    subgenres: ['Vertical shmup', 'Horizontal shmup', 'Bullet-hell', 'Arcade shmup'],
    tags: ['Action', 'Precision', 'Arcade', 'High score'],
  },
  {
    id: 'tradingcardgame',
    name: 'Trading Card Game',
    summary: 'Physical or digital card games where players collect, trade, and build decks to compete.',
    mechanics: ['Card collecting', 'Deck building', 'Card trading', 'Rarity tiers', 'Competitive play'],
    famousGames: ['Pokemon Trading Card Game', 'Yu-Gi-Oh!', 'Magic: The Gathering'],
    subgenres: ['Fantasy TCG', 'Anime TCG', 'Sports TCG', 'Digital TCG'],
    tags: ['Collecting', 'Trading', 'Competitive', 'Community'],
  },
  {
    id: 'autobattler',
    name: 'Auto-Battler',
    summary: 'Strategy games where you assemble and position units that fight automatically, then watch them battle.',
    mechanics: ['Unit recruitment', 'Positioning strategy', 'Synergy exploitation', 'Automatic combat', 'Economic management'],
    famousGames: ['Dota Auto Chess', 'Teamfight Tactics', 'Underlords'],
    subgenres: ['Synergy-focused auto-battler', 'Draft-based auto-battler', 'Fast auto-battler', 'Complex auto-battler'],
    tags: ['Strategy', 'Composition', 'Synergy', 'Competitive'],
  },
];

export const genreGuideContext = genreGuideEntries
  .map((genre) => {
    return [
      `${genre.name} (${genre.id}) - /genres/${genre.id}`,
      `Summary: ${genre.summary}`,
      `Mechanics: ${genre.mechanics.join(', ')}`,
      `Famous games: ${genre.famousGames.join(', ')}`,
      `Subgenres: ${genre.subgenres.join(', ')}`,
      `Tags: ${genre.tags.join(', ')}`,
    ].join('\n');
  })
  .join('\n\n');
